version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev -- --host

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/ifixitt
      - PORT=5000
      - NODE_ENV=development
      - JWT_SECRET=your-secret-key-change-in-production
      - SESSION_SECRET=your-session-secret-change-in-production
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ifixitt
    command: mongod --quiet --logpath /dev/null

volumes:
  mongodb_data: 